//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRR.Models.Stored_Procedures
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class CRRStoredProcedures : DbContext
    {
        public CRRStoredProcedures()
            : base("name=CRRStoredProcedures")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual ObjectResult<CRR_FastShiftData_Result> CRR_FastShiftData(Nullable<System.DateTime> iFromDate, Nullable<System.DateTime> iToDate)
        {
            var iFromDateParameter = iFromDate.HasValue ?
                new ObjectParameter("iFromDate", iFromDate) :
                new ObjectParameter("iFromDate", typeof(System.DateTime));
    
            var iToDateParameter = iToDate.HasValue ?
                new ObjectParameter("iToDate", iToDate) :
                new ObjectParameter("iToDate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CRR_FastShiftData_Result>("CRR_FastShiftData", iFromDateParameter, iToDateParameter);
        }
    
        public virtual ObjectResult<CRR_ProductDetails_Result> CRR_ProductDetails(string codeFA)
        {
            var codeFAParameter = codeFA != null ?
                new ObjectParameter("CodeFA", codeFA) :
                new ObjectParameter("CodeFA", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CRR_ProductDetails_Result>("CRR_ProductDetails", codeFAParameter);
        }
    
        public virtual ObjectResult<CRR_WorkCenter_Result> CRR_WorkCenter()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CRR_WorkCenter_Result>("CRR_WorkCenter");
        }
    
        public virtual ObjectResult<CRR_Department_Result> CRR_Department()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CRR_Department_Result>("CRR_Department");
        }
    
        public virtual ObjectResult<CRR_QTMData_Result> CRR_QTMData(Nullable<System.DateTime> dtBegin, Nullable<System.DateTime> dtLast)
        {
            var dtBeginParameter = dtBegin.HasValue ?
                new ObjectParameter("dtBegin", dtBegin) :
                new ObjectParameter("dtBegin", typeof(System.DateTime));
    
            var dtLastParameter = dtLast.HasValue ?
                new ObjectParameter("dtLast", dtLast) :
                new ObjectParameter("dtLast", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CRR_QTMData_Result>("CRR_QTMData", dtBeginParameter, dtLastParameter);
        }
    
        public virtual ObjectResult<CRR_VisualData_Result> CRR_VisualData(Nullable<System.DateTime> dtBegin, Nullable<System.DateTime> dtLast)
        {
            var dtBeginParameter = dtBegin.HasValue ?
                new ObjectParameter("dtBegin", dtBegin) :
                new ObjectParameter("dtBegin", typeof(System.DateTime));
    
            var dtLastParameter = dtLast.HasValue ?
                new ObjectParameter("dtLast", dtLast) :
                new ObjectParameter("dtLast", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CRR_VisualData_Result>("CRR_VisualData", dtBeginParameter, dtLastParameter);
        }
    
        public virtual ObjectResult<CRR_RunningTime_Result> CRR_RunningTime(Nullable<System.DateTime> iFromDate, Nullable<System.DateTime> iToDate)
        {
            var iFromDateParameter = iFromDate.HasValue ?
                new ObjectParameter("iFromDate", iFromDate) :
                new ObjectParameter("iFromDate", typeof(System.DateTime));
    
            var iToDateParameter = iToDate.HasValue ?
                new ObjectParameter("iToDate", iToDate) :
                new ObjectParameter("iToDate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CRR_RunningTime_Result>("CRR_RunningTime", iFromDateParameter, iToDateParameter);
        }
    
        public virtual ObjectResult<CRR_CigaretteSpecifications_Result> CRR_CigaretteSpecifications(string iOrderNo)
        {
            var iOrderNoParameter = iOrderNo != null ?
                new ObjectParameter("iOrderNo", iOrderNo) :
                new ObjectParameter("iOrderNo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CRR_CigaretteSpecifications_Result>("CRR_CigaretteSpecifications", iOrderNoParameter);
        }
    
        public virtual ObjectResult<Nullable<double>> CRR_CigaretteWeight(string iOrderNo)
        {
            var iOrderNoParameter = iOrderNo != null ?
                new ObjectParameter("iOrderNo", iOrderNo) :
                new ObjectParameter("iOrderNo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<double>>("CRR_CigaretteWeight", iOrderNoParameter);
        }
    
        public virtual ObjectResult<CRR_ProcessOrderList_Result> CRR_ProcessOrderList(Nullable<System.DateTime> iToDAte, Nullable<System.DateTime> iFromDAte, string iLinkupID)
        {
            var iToDAteParameter = iToDAte.HasValue ?
                new ObjectParameter("iToDAte", iToDAte) :
                new ObjectParameter("iToDAte", typeof(System.DateTime));
    
            var iFromDAteParameter = iFromDAte.HasValue ?
                new ObjectParameter("iFromDAte", iFromDAte) :
                new ObjectParameter("iFromDAte", typeof(System.DateTime));
    
            var iLinkupIDParameter = iLinkupID != null ?
                new ObjectParameter("iLinkupID", iLinkupID) :
                new ObjectParameter("iLinkupID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CRR_ProcessOrderList_Result>("CRR_ProcessOrderList", iToDAteParameter, iFromDAteParameter, iLinkupIDParameter);
        }
    }
}
